DROP TABLE IF EXISTS "dogs";

CREATE TABLE "dogs" (
	"id" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"breed" VARCHAR(255) NOT NULL,
	"age" INT NOT NULL,
	"photograph" VARCHAR(255) NOT NULL
);

SELECT * FROM "dogs";
